apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: go-gateway-monitor
    labels:
        release: prometheus # must match helm release name in ./deploy.sh hpa-stack
spec:
    namespaceSelector:
        matchNames:
            - default
    selector:
        matchLabels:
            app: go-gateway
    endpoints:
        - port: web
          path: /metrics
          interval: 15s
